- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs:20 version
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs:20 vertsion
  ansible.builtin.package:
    name: nodejs
    state: present

# for npm dependencies, the is no ansibile module, but community module is there
- name: Install dependencies for npm 
  community.general.npm:
    path: /app