- name: Install python3 gcc python3-devel
  ansible.builtin.package:
    name: "{{ item }}"
    state: installed
  loop:
  - python3
  - gcc
  - python3-devel

- name: install dependencoes
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app