# Creating servive file for catalogue and this an task,

- name: copy catalogue service to /etc/systemd/system/catalogue.service location
  ansible.builtin.template:  #we have changed copy to template in module, because of we are using catalogue .service in this templates folder
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

#deamon reload
- name: daemon reload - systemd - systemctl
  ansible.builtin.systemd_service:
    daemon_reload: true

# start and enable catalogue service
- name: start and enable catalogue service
  ansible.builtin.service:
    name: catalogue
    state: restarted #even if app is not running we can restart it
    enabled: yes